/*
 * The namespace Roadbed.Scheduling.Dtos was removed on purpose and replaced with Roadbed.Crud so that no additional using statements are required.
 */
namespace Roadbed.Scheduling;

using System;

/// <summary>
/// Immutable record containing all information about a job execution.
/// </summary>
/// <remarks>
/// This record is populated by the metrics listener and passed to ISchedulingMetrics implementations.
/// Contains job identification, trigger information, timing data, and optional result message set by the job.
/// All timing properties are nullable as they may not be available for certain events (e.g., misfires).
/// </remarks>
public sealed record JobExecutionInfo
{
    #region Public Properties

    /// <summary>
    /// Gets the unique identifier for this specific execution instance.
    /// </summary>
    /// <remarks>
    /// Generated by Quartz.NET for each job execution.
    /// For misfires, this is generated as a new GUID since Quartz does not provide one.
    /// </remarks>
    required public string FireInstanceId { get; init; }

    /// <summary>
    /// Gets the actual time the trigger fired and the job started executing.
    /// </summary>
    /// <remarks>
    /// Null for misfire events where the job did not actually execute.
    /// </remarks>
    public DateTimeOffset? FireTimeUtc { get; init; }

    /// <summary>
    /// Gets the job group name.
    /// </summary>
    /// <remarks>
    /// Used for organizing jobs into logical groups. Defaults to "Default" if not specified.
    /// </remarks>
    required public string JobGroup { get; init; }

    /// <summary>
    /// Gets the unique job name.
    /// </summary>
    /// <remarks>
    /// Combined with JobGroup forms a unique JobKey in Quartz.NET.
    /// </remarks>
    required public string JobName { get; init; }

    /// <summary>
    /// Gets the next scheduled fire time for the trigger.
    /// </summary>
    /// <remarks>
    /// Null if there is no next scheduled execution (e.g., one-time job completed).
    /// </remarks>
    public DateTimeOffset? NextFireTimeUtc { get; init; }

    /// <summary>
    /// Gets the previous fire time before this execution.
    /// </summary>
    /// <remarks>
    /// Null for the first execution of a trigger.
    /// </remarks>
    public DateTimeOffset? PreviousFireTimeUtc { get; init; }

    /// <summary>
    /// Gets the optional result message set by the job via Context.Result.
    /// </summary>
    /// <remarks>
    /// Jobs can set this.Context.Result to provide a summary of their execution.
    /// Examples: "Processed 1,234 records", "Deleted 56 files, freed 2.3 GB", etc.
    /// This message is included in metrics reporting.
    /// </remarks>
    public string? ResultMessage { get; init; }

    /// <summary>
    /// Gets the scheduled fire time for the trigger.
    /// </summary>
    /// <remarks>
    /// This is when the trigger was supposed to fire based on the schedule.
    /// May differ from FireTimeUtc if the job was delayed or misfired.
    /// Null for misfire events.
    /// </remarks>
    public DateTimeOffset? ScheduledFireTimeUtc { get; init; }

    /// <summary>
    /// Gets the trigger group name.
    /// </summary>
    /// <remarks>
    /// Triggers are organized into groups similar to jobs.
    /// </remarks>
    required public string TriggerGroup { get; init; }

    /// <summary>
    /// Gets the trigger name.
    /// </summary>
    /// <remarks>
    /// Combined with TriggerGroup forms a unique TriggerKey in Quartz.NET.
    /// </remarks>
    required public string TriggerName { get; init; }

    #endregion Public Properties
}